# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest version from their GitHub releases
    hooks:
      - id: trailing-whitespace
